# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
      - development

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Auto Pull Request
        uses: diillson/auto-pull-request@latest
        with:
          destination_branch: "release"
