name: Automated Release Process

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Unlock Release Branch
        run: |
          echo "Unlocking release branch (if applicable)"

      - name: Merge Development into Release
        run: |
          if git show-ref --verify --quiet refs/heads/release; then
            git checkout release
          else
            git checkout -b release
          fi
          git merge development

      - name: Push Changes
        run: |
          git push origin release

      - name: Lock Release Branch
        run: |
          echo "Locking release branch (if applicable)"
