# File: .github/workflows/pull-request.yml
on:
  push:
    branches:
      - development
jobs:
  check-user:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub user
        run: |
          echo "Current GitHub user: $(git config --global user.name)"
          echo "Current GitHub email: $(git config --global user.email)"

  pull-request:
    runs-on: ubuntu-latest
    needs: check-user  # This ensures the user check runs before the pull request job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Update Homebrew
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update

      - name: Install hub
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install hub
      
      - name: Auto Pull Request
        uses: diillson/auto-pull-request@latest
        with:
          destination_branch: "release"
