name: Automated Release Process

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Unlock Release Branch
        run: |
          echo "Unlocking release branch (if applicable)"

      - name: Merge Development Changes into Release
        run: |
          # Check if the release branch exists and check it out
          if git show-ref --verify --quiet refs/heads/release; then
            git checkout release
          else
            git checkout -b release
          fi

          # Fetch remote changes
          git fetch origin release

          # Merge remote release branch allowing unrelated histories
          git merge origin/release --allow-unrelated-histories

          # Merge changes from development into release
          git merge development

      - name: Push Changes
        run: |
          git push origin release

      - name: Lock Release Branch
        run: |
          echo "Locking release branch (if applicable)"
