name: On Pull Request Opened

on:
  pull_request:
    branches: [ development ]

jobs:
  lint:
    name: Sona Code Check
    uses: ./.github/workflows/SonaCloud Build.yml

  test:
    name: .net Check Build Validation
    uses: ./.github/workflows/.net Build Checker.yml